export { Login } from './login'
export { LoginCode } from './login-code'
export { TeacherInformation } from './information-teacher'
export { StudentInformation } from './information-student'
export { PatriarchOneInformation } from './information-patriarchOne'
export { PatriarchTwoInformation } from './information-patriarchTwo'
