export const gap = {
  "gap-xxs": 5,
  "gap-xs": 10,
  "gap-s": 15,
  "gap-m": 18,
  "gap-l": 20,
  "gap-xl": 25,
  "gap-xxl": 30,
  "gap-xxxl": 50,
  "gap-xxxxl": 54,
  "icon-width": 22,
  "icon-height": 22,
  "button-height-s": 20,
  "button-height": 44,
  "button-height-l": 50,
  "nav-height": 44,
  "row-height": 50,
  "row-height-s": 44,
}